configfile: "workflow_config.yaml"

plot_styles = config["plot_styles"]
plot_filetype = config["plot_filetype"]

ensembles = ["M1", "M2", "M3", "M4", "M5"]


include: "rules/gradient_flow.smk"
include: "rules/package.smk"
include: "rules/mass.smk"
include: "rules/plaquette.smk"
include: "rules/combined_plots.smk"
include: "rules/spectrum_plots.smk"
include: "rules/spectrum_tables.smk"
include: "rules/extrapolation.smk"
include: "rules/cb_autocorrelation_decay_const.smk"
include: "rules/spectral_densities.smk"


h5_data = expand(
    "data_assets/{data}.h5",
    data=["wall_correlators"],
)

plots = expand(
    f"assets/plots/{{plot}}.{plot_filetype}",
    plot=[
        "wall_comparison",
        "final_spectrum_MN3",
        "final_spectrum_detail",
        "matrixel_fundamental_antisymmetric",
        "matrixel_chimera_baryons",
        "LambdaScan",
        "spectral_density_single_gaussian",
    ],
)
tables = expand(
    f"assets/tables/{{table}}.tex",
    table=[
        "local_smeared_decay_constants",
        "ensembles",
    ] + expand(
        "{ensemble}_output_table_aE{n}_meson",
        ensemble=ensembles,
        n=[0, 1, 2],
    ) + expand(
        "{ensemble}_output_table_CB_aE{n}",
        ensemble=ensembles,
        n=[0, 1, 2],
    ) + expand(
        "{ensemble}_output_table_matrix_CB",
        ensemble=ensembles,
    ),
)


rule all:
    input:
        h5_data=h5_data,
        plots=plots,
        tables=tables,
