include: "rules/gradient_flow.smk"
include: "rules/package.smk"
include: "rules/mass.smk"
include: "rules/plaquette.smk"
include: "rules/combined_plots.smk"
include: "rules/spectrum_plots.smk"
include: "rules/spectrum_tables.smk"
include: "rules/extrapolation.smk"


#plot_styles = "styles/paperdraft.mplstyle"
plot_filetype = "pdf"

h5_data = expand(
    "data_assets/{datafile}.h5",
    datafile=["correlators_wall", "correlators_smear", "flows"],
)

topology_history_plots = [
    f"top_charge_history_{ensemble}"
    for ensemble in [
        "Sp4b6.7nAS3mAS-1.045T48L24",
        "Sp4b6.7nAS3mAS-1.067T54L36",
        "Sp4b6.8nAS3mAS-1.035T56L24",
        "Sp4b6.8nAS3mAS-1.046T54L36",
    ]
]
plots = expand(
    f"assets/plots/{{plot}}.{plot_filetype}",
    plot=[
        "table_V_decay"
    ],
)
tables = expand(
    f"assets/tables/{{table}}.tex",
    table=[
        #"plaquette_table",
        #"gflow_table",
        "table_V_decay",
        "table_V_mass",
        "table_VI",
        "table_VII",
        "table_VIII",
        "table_IX",
        "table_X",
        "table_XI",
        "table_XII",
    ],
)


rule all:
    input:
        h5_data=h5_data,
        plots=plots,
        tables=tables,
